version: '3'
services:

  database:
    build: ./database
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE : 'fitness_app'
      MYSQL_ROOT_PASSWORD: 'root'
    ports: 
      - '3306:3306'

